### ISSUE TITLE
Hello, not sure if you still keep this updated. But I am getting an error of "'downloadRelease" is not a function

### ISSUE THREAD

**Issue by HappyZombies** [stephan83/download-github-release#1]
Hello there, I stumbled upon this because I was having trouble getting a download from my assets directory via the API. It works great, but I need to do some more processing after the download is completed. I found that doing downloadRelease.default() works but the .then promise methods do not get called...

**Comment by stephan83** [comment]
Sorry I was on holiday. I'll look into it.
