### ISSUE TITLE
Option to NOT extract zipfiles?

### ISSUE THREAD

**Issue by billiegoose** [stephan83/download-github-release#2]
This module is almost perfect for my needs, but I need the raw files to do checksums & binary comparisons and whatnot. Also, one of the archives created an invalid filename on Windows so the unzipping crashed the rest of the downloads. Would you accept a pull request making the zipfile extraction optional with a command line flag like `-x` for `--extract`?

**Comment by stephan83** [comment]
Yes that's a planned feature

**Comment by stephan83** [comment]
And you are welcome to do a pull request :)

**Comment by billiegoose** [comment]
Awesome! lemme find where I put my fork and see what state it's in
